yolo:
  cfg_path: '/usr/src/models/yolo_data/yolov3-spp.cfg'
  weights_path: '/usr/src/models/yolo_data/yolov3-spp-ultralytics.pt'
  names_path: '/usr/src/models/yolo_data/coco.names'
  img_size: 512
  gpu_id: '0'
  half: False

vibe:
  root_dir: '/usr/src/models/vibe_data'
  seqlen: 1
  scale: 1.1
  crop_size: 224
  gpu_id: '0'

lwgan:
  gen_name: "holoportator"
  image_size: 256
  bg_ks: 11
  ft_ks: 3
  has_detector: False
  post_tune: False
  front_warp: False
  save_res: False
  n_threads_test: 4
  load_path: '/usr/src/models/lwgan_data/net_epoch_20_id_G.pth'
  smpl_model: '/usr/src/models/lwgan_data/smpl_model.pkl'
  hmr_model: '/usr/src/models/lwgan_data/hmr_tf2pt.pth'
  smpl_faces: '/usr/src/models/lwgan_data/smpl_faces.npy'
  uv_mapping: '/usr/src/models/lwgan_data/mapper.txt'
  part_info: '/usr/src/models/lwgan_data/smpl_part_info.json'
  front_info: '/usr/src/models/lwgan_data/front_facial.json'
  head_info: '/usr/src/models/lwgan_data/head.json'
  face_model: '/usr/src/models/lwgan_data/sphere20a_20171020.pth'
  maskrcnn_path: '/usr/src/models/lwgan_data/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth'
  gpu_ids: '0'

segmentator:
  maskrcnn_path: '/usr/src/models/lwgan_data/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth'
  ks: 1
  gpu_id: '0'

lwgan_ada:
  dataset_size: 200
  intervals: 1
  data_dir: '/usr/src/app/outputs/ada/datasets/last'
  checkpoints_dir: '/usr/src/app/outputs/ada/output'
  load_path: '/usr/src/models/lwgan_data/net_epoch_20_id_G.pth'
  load_D_path: '/usr/src/models/lwgan_data/net_epoch_20_id_D.pth'
  smpl_model: '/usr/src/models/lwgan_data/smpl_model.pkl'
  hmr_model: '/usr/src/models/lwgan_data/hmr_tf2pt.pth'
  smpl_faces: '/usr/src/models/lwgan_data/smpl_faces.npy'
  uv_mapping: '/usr/src/models/lwgan_data/mapper.txt'
  part_info: '/usr/src/models/lwgan_data/smpl_part_info.json'
  front_info: '/usr/src/models/lwgan_data/front_facial.json'
  head_info: '/usr/src/models/lwgan_data/head.json'
  face_model: '/usr/src/models/lwgan_data/sphere20a_20171020.pth'
  maskrcnn_path: '/usr/src/models/lwgan_data/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth'
  dataset_mode: 'Ada'
  images_folder: 'imgs'
  smpls_folder: 'smpls'
  model: 'holoportator_trainer'
  gen_name: 'holoportator'
  image_size: 256
  lambda_rec: 10.0
  lambda_tsf: 10.0
  lambda_face_: 5.0
  lambda_face: 10.0
  lambda_style: 0.0
  lambda_mask_: 1.0
  lambda_mask: 0.0
  lambda_mask_smooth_: 1.0
  lambda_mask_smooth: 0.0
  name: 'ada_last'
  mask_bce: True
  use_vgg: True
  use_face: True
  use_style: False  
  train_D: True
  lr_G: 0.0002
  nepochs_no_decay: 4
  nepochs_decay: 2
  batch_size: 14
  gpu_ids: '0'

input:
  warmup_img: '/usr/src/data/holovideo/samples/img0.jpeg'
  frames_dir: '/usr/src/data/holovideo/frames'
  target_path: 'person_2/light-100_temp-5600/garments_2/front_position/cam1'
  view: 'R=0,0,0/t=0,0,0'
  steps: 1
  scene_bbox: '290,10,700,700'
  target_fps: 20

output:
  result_dir: '/usr/src/app/outputs/yolo_vibe_lwgan/t1'


